on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.ts'


jobs:
  compile:
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install packages
        run: npm install
      - name: Compile TS -> JS
        run: |
          cd src
          npx tsc
          cd ../
      - name: Commit changes
        run: |
          git config --local user.email "actions@git.polymodloader.com"
          git config --local user.name "Forgejo Actions"
          git add PolyModLoader.d.ts PolyModLoader.js PolyTypes.d.ts PolyTypes.js
          git commit -m "[no ci] Compile TS -> JS: ${{ github.event.head_commit.message }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.FORGEJO_TOKEN }}