name: Update pages branch

on:
  push:
    tags:
      - "v0.6.*"

jobs:
  update-pages:
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up packages
        run: apt-get update && apt-get install -y jq

      - name: Write PML build to package.json
        env:
          TAG: ${{ forgejo.ref_name }}
        run: |
          TAG_CLEAN="${TAG#v}"

          VERSION=$(echo "$TAG_CLEAN" | cut -d'-' -f1)   # 0.6.0
          BUILD=$(echo "$TAG_CLEAN" | cut -d'-' -f2)     # 1

          npm version "$VERSION" --no-git-tag-version --allow-same-version
          jq --arg b "$BUILD" '.pmlBuild = $b' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Clean up repo
        run: rm -rf .gitignore .forgejo *.ts src README.md electron pnpm-lock.yaml package-lock.json .DS_Store

      - name: Commit to pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          git config --local user.email "actions@git.polymodloader.com"
          git config --local user.name "Forgejo Actions"
          git checkout --orphan pages || git checkout pages
          git rm -rf . --cached || true
          git add -A
          git diff --cached --quiet || git commit -m "update pages branch"
          git push -u origin pages --force