when:
  event: [ tag ]

steps:
- name: make folder structure
  image: node:25-trixie
  environment:
    ANDROID_KEYSTORE_B64:
      from_secret: ANDROID_KEYSTORE_B64
  commands:
  - apt-get update > /dev/null && apt-get install -y rsync curl > /dev/null

  # Base layout
  - mkdir -p temp temp/pml platforms

  # Copy repo into temp/pml, excluding CI + build dirs
  - rsync -a --quiet --exclude=temp/ --exclude=.git/ --exclude=.woodpecker/ ./ temp/pml/

  # Get keystore
  - mkdir -p keys
  - printf '%s' "$ANDROID_KEYSTORE_B64" | base64 -d > keys/debug.keystore

- name: write PML build to package.json
  image: node:25-trixie
  commands:
  - |
    sed -i "s/\"pmlBuild\": \".*\"/\"pmlBuild\": \"${CI_COMMIT_TAG}\"/" temp/pml/package.json

- name: Install npm packages
  image: node:25-trixie
  commands:
  - |
    (
      cd temp/pml
      npm install
    )

- name: build and compress windows
  image: node:25-trixie
  commands:
  - apt-get update > /dev/null && apt-get install -y zip > /dev/null
  - |
    cd temp/pml
    npm run package-win
    zip -rq ../../platforms/windows.zip PolyModLoader-win32-x64

- name: build and compress linux
  image: node:25-trixie
  commands:
  - |
    cd temp/pml
    npm run package-linux
    tar -czf ../../platforms/linux.tar.gz PolyModLoader-linux-x64
  - cp temp/pml/PolyModLoader-linux-x64/resources/app.asar temp/app.asar

- name: build and compress macos
  image: node:25-trixie
  commands:
  - apt-get update > /dev/null && apt-get install -y zip > /dev/null
  - |
    cd temp/pml
    npm run package-mac
    zip -rq ../../platforms/macos.zip PolyModLoader-darwin-x64

- name: build Android
  image: node:25-trixie
  environment:
    APKSIGNER_JAR: apksigner.jar
  commands:
  - apt-get update > /dev/null && apt-get install -y curl zip unzip openjdk-21-jre android-sdk-build-tools rsync > /dev/null
  - mkdir -p platforms/android
  - curl -fsSL -o temp/android.zip https://fs.crjakob.com/pmlbuild/android.zip
  - unzip -qo temp/android.zip -d platforms/android
  - mv platforms/android/android/* platforms/android/
  - rmdir platforms/android/android
  - rsync -a --quiet \ --exclude=platforms --exclude=node_modules --exclude=PolyModLoader-win32-x64 --exclude=PolyModLoader-linux-x64 --exclude=PolyModLoader-darwin-x64 temp/pml/ platforms/android/PolyTrack/assets/public/
  - |
    (
      cd platforms/android/PolyTrack
      zip -rq -0 ../../PolyTrack.apk .
    )
  - |
    apksigner sign \
      --ks keys/debug.keystore \
      --ks-key-alias polytrack \
      --ks-pass pass:android \
      --key-pass pass:android \
      platforms/PolyTrack.apk
    apksigner verify --verbose platforms/PolyTrack.apk

- name: list files
  image: node:25-trixie
  commands:
  - ls -RA

- name: make release
  image: woodpeckerci/plugin-release
  settings:
    title: Version ${CI_COMMIT_TAG}
    note: Automated release for ${CI_COMMIT_TAG}
    files:
    - platforms/windows.zip
    - platforms/macos.zip
    - platforms/linux.tar.gz
    - platforms/PolyTrack.apk
    - temp/app.asar
    api-key:
      from_secret: CODEBERG_TOKEN
