when:
  event: [ tag ]

steps:
- name: make folder structure
  image: node:20-bullseye
  environment:
    ANDROID_KEYSTORE_B64:
      from_secret: ANDROID_KEYSTORE_B64
  commands:
  - apt-get update > /dev/null && apt-get install -y rsync curl > /dev/null

  # Base layout
  - mkdir -p temp temp/pml platforms

  # Copy repo into temp/pml, excluding CI + build dirs
  - rsync -a --quiet --exclude=temp/ --exclude=.git/ --exclude=.woodpecker/ ./ temp/pml/

  # Get keystore
  - mkdir -p keys
  - printf '%s' "$ANDROID_KEYSTORE_B64" | base64 -d > keys/debug.keystore

- name: write PML version to PolyModLoader.js
  image: node:20-bullseye
  commands:
  - |
    # Inject version into PolyModLoader.js
    sed -i \
      "s|const pmlversion = await fetch([^;]*);|const pmlversion = \"$CI_COMMIT_TAG\";|" \
      temp/pml/PolyModLoader.js

- name: build Android
  image: node:20-bullseye
  environment:
    APKSIGNER_JAR: apksigner.jar
  commands:
  - apt-get update > /dev/null && apt-get install -y curl zip unzip openjdk-17-jre-headless android-sdk-build-tools > /dev/null
  - mkdir -p platforms/android

  - curl -fsSL -o temp/android.zip https://fs.crjakob.com/pmlbuild/android.zip
  - unzip -qo temp/android.zip -d platforms/android

  - mv platforms/android/android/* platforms/android/ > /dev/null
  - rmdir platforms/android/android

  - cp -r temp/pml/* platforms/android/PolyTrack/assets/public/ > /dev/null

  - |
    (
      cd platforms/android/PolyTrack
      zip -rq -0 ../../PolyTrack.apk .
    )

  - |
    apksigner sign \
      --ks keys/debug.keystore \
      --ks-key-alias polytrack \
      --ks-pass pass:android \
      --key-pass pass:android \
      platforms/PolyTrack.apk

    apksigner verify --verbose platforms/PolyTrack.apk

- name: compile asar
  image: node:20-bullseye
  commands:
  - npm install -g asar > /dev/null
  - npx asar p temp/pml temp/app.asar

- name: build windows
  image: node:20-bullseye
  commands:
  - apt-get update > /dev/null && apt-get install -y zip unzip curl > /dev/null
  - mkdir -p platforms/windows

  - curl -fsSL -o temp/windows.zip https://fs.crjakob.com/pmlbuild/windows.zip
  - unzip -qo temp/windows.zip -d platforms/windows

  - cp temp/app.asar platforms/windows/resources/app.asar > /dev/null

  - zip -rq platforms/windows.zip platforms/windows

- name: build macOS
  image: node:20-bullseye
  commands:
  - apt-get update > /dev/null && apt-get install -y zip unzip curl > /dev/null
  - mkdir -p platforms/macos

  - curl -fsSL -o temp/macos.zip https://fs.crjakob.com/pmlbuild/macos.zip
  - unzip -qo temp/macos.zip -d platforms/macos

  - cp temp/app.asar platforms/macos/PolyTrack.app/Contents/Resources/app.asar > /dev/null

  - zip -rq platforms/macos.zip platforms/macos

- name: build linux
  image: node:20-bullseye
  commands:
  - apt-get update > /dev/null && apt-get install -y curl unzip > /dev/null
  - mkdir -p platforms/linux

  - curl -fsSL -o temp/linux.zip https://fs.crjakob.com/pmlbuild/linux.zip
  - unzip -qo temp/linux.zip -d platforms/linux

  - cp temp/app.asar platforms/linux/resources/app.asar > /dev/null

  - tar -czf platforms/linux.tar.gz platforms/linux > /dev/null

- name: make release
  image: woodpeckerci/plugin-release
  settings:
    title: Version ${CI_COMMIT_TAG}
    note: Automated release for ${CI_COMMIT_TAG}
    files:
    - platforms/windows.zip
    - platforms/macos.zip
    - platforms/linux.tar.gz
    - platforms/PolyTrack.apk
    - temp/app.asar
    api-key:
      from_secret: CODEBERG_TOKEN

- name: notify discord bot
  image: curlimages/curl
  environment:
    CI_TOKEN:
      from_secret: DISCORD_CI_TOKEN
  commands:
  - |
    curl -s -X POST https://bot.polymodloader.com/ci \
      -H "Authorization: Bearer $CI_TOKEN" \
      -H "Content-Type: application/json" \
      -d '{
        "guild_id": "1387368500435353610",
        "channel_id": "1470031669007483033",
        "content": "## **Version '"$CI_COMMIT_TAG"' of the PML app has been released!**\nYou can download it here: https://codeberg.org/'"$CI_REPO"'/releases/tag/'"$CI_COMMIT_TAG"'\n|| <@&1387377745868099699> ||"
      }'
